### ISSUE TITLE
Problem setting up Tiles Caching

### ISSUE THREAD

**Issue by CrazyWolf13** [dedicatedcode/reitti#572]
**Describe the bug**
Hi, I'm one of the maintainer from the community-scripts for the proxmox script of reitti (https://community-scripts.github.io/ProxmoxVE/scripts?id=reitti) Since v3.0.0 the map does not load at all, I guess this is related to the tiles caching?

As in proxmox enviroment we do not use docker we use LXC e.g execute the commands as if they would be bare metal.

I did the following:

**To Reproduce**
```bash
mkdir -p /var/cache/nginx/tiles
cat > /etc/nginx/nginx.conf << 'EOF'
    events {
      worker_connections 1024;
    }
    http {
      proxy_cache_path /var/cache/nginx/tiles levels=1:2 keys_zone=tiles:10m max_size=1g inactive=30d use_temp_path=off;

      server {
        listen 80;
        location / {
          proxy_pass https://tile.openstreetmap.org/;
          proxy_set_header Host tile.openstreetmap.org;
          proxy_set_header User-Agent "Reitti/1.0";
          proxy_cache tiles;
          proxy_cache_valid 200 30d;
          proxy_cache_use_stale error timeout updating http_500 http_502 http_503 http_504;
        }
      }
    }
EOF
apt install -y nginx
# Starting nginx here just manually to test
nginx -g 'daemon off;'
```

After that reitti still shows the error:

```bash
Dec 20 23:27:35 reitti java[410]: 2025-12-20T23:27:35.969+01:00  WARN 410 --- [io-8080-exec-27] c.d.r.c.api.TileProxyController          : Failed to fetch tile 13/4279/2872: URI is not absolute
Dec 20 23:27:35 reitti java[410]: 2025-12-20T23:27:35.970+01:00  WARN 410 --- [io-8080-exec-28] c.d.r.c.api.TileProxyController          : Failed to fetch tile 13/4278/2876: URI is not absolute
Dec 20 23:27:35 reitti java[410]: 2025-12-20T23:27:35.975+01:00  WARN 410 --- [io-8080-exec-21] c.d.r.c.api.TileProxyController          : Failed to fetch tile 13/4279/2875: URI is not absolute
```

**Expected behavior**
It should now be working? or what else is needed when using direct bare metal deployment?

**Desktop (please complete the following information):**
 - OS: Debian 13
 - Browser Firefox Webkit
 - Version 146.0

**Smartphone (please complete the following information):**
 - Device: S25 Ultra
 - OS: Android 16
 - Browser Firefox 
 - Version 146.0

**Additional context**
Thanks for any tips!

**Comment by dgraf-gh** [comment]
Hi @CrazyWolf13,

it seems like there is a bug in the initializing of the TilesProxyController. The plan was to skip this if `reitti.ui.tiles.cache.url` is not set, but this does not work as expected.

In the meantime you need to set `reitti.ui.tiles.cache.url` in the application.properties to the appropriate value. For docker it is set to `http://tile-cache`. I think that is the right place when using proxmox.


Big thanks to you for providing these scripts ❤️  

Edit: I just clicked the release button for [v3.0.1](https://github.com/dedicatedcode/reitti/releases/tag/v3.0.1). This should fix the issue when no tiles cache is set.

**Comment by CrazyWolf13** [comment]
Good Morning @dgraf-gh 
Perfect, I updated to 3.0.1 and added:
```bash
reitti.ui.tiles.cache.url=http://localhost
```

Which made the map appear, though it only seems to load the initial place detailed and after that it does not load anymore parts of the map detailed.

Also the logs show this, any ideas?

```bash
Dec 21 10:34:36 reitti java[10039]: 2025-12-21T10:34:36.745+01:00  WARN 10039 --- [o-8080-exec-103] c.d.r.c.api.TileProxyController          : Failed to fetch tile 14/8580/5739: 502 Bad Gateway on GET request for "http://localhost/14/8580/5739.png": "<html><EOL><EOL><head><title>502 Bad Gateway</title></head><EOL><EOL><body><EOL><EOL><center><h1>502 Bad Gateway</h1></center><EOL><EOL><hr><center>nginx/1.26.3</center><EOL><EOL></body><EOL><EOL></html><EOL><EOL>"
Dec 21 10:34:36 reitti java[10039]: 2025-12-21T10:34:36.746+01:00  WARN 10039 --- [o-8080-exec-123] c.d.r.c.api.TileProxyController          : Failed to fetch tile 14/8580/5745: 502 Bad Gateway on GET request for "http://localhost/14/8580/5745.png": "<html><EOL><EOL><head><title>502 Bad Gateway</title></head><EOL><EOL><body><EOL><EOL><center><h1>502 Bad Gateway</h1></center><EOL><EOL><hr><center>nginx/1.26.3</center><EOL><EOL></body><EOL><EOL></html><EOL><EOL>"
```

**Comment by dgraf-gh** [comment]
Maybe try it with 127.0.0.1 instead of localhost. I had a problem inside the nginx container where curl http://localhost/... worked, but wget http://localhost ... not. Maybe a similar problem. 

But, based on the error it seems like the connection to the nginx works but then the nginx can't fetch the data from osm. I am a little bit confused that the initial tiles load. But this can also be cached in your browser. Maybe try reloading it with ctrl+shift+r

But ypu should see something in the nginx log

**Comment by CrazyWolf13** [comment]
I don't really see a big difference with 127.0.0.1 instead of localhost.

nginx error log shows nothing and accesslog just successes:

```bash
127.0.0.1 - - [21/Dec/2025:11:08:56 +0100] "GET /14/8562/5742.png HTTP/1.1" 200 16919 "-" "Java/25.0.1"
127.0.0.1 - - [21/Dec/2025:11:08:56 +0100] "GET /14/8562/5743.png HTTP/1.1" 200 23322 "-" "Java/25.0.1"
127.0.0.1 - - [21/Dec/2025:11:08:56 +0100] "GET /14/8577/5738.png HTTP/1.1" 200 26430 "-" "Java/25.0.
```

While I still see this error seemingly coming from reitti:

I traced the same tiles:
```bash
Dec 21 11:11:05 reitti java[10786]: 2025-12-21T11:11:05.446+01:00  WARN 10786 --- [o-8080-exec-199] c.d.r.c.api.TileProxyController          : Failed to fetch tile 13/4292/2781: 502 Bad Gateway on GET request for "http://127.0.0.1/13/4292/2781.png": "<html><EOL><EOL><head><title>502 Bad Gateway</title></head><EOL><EOL><body><EOL><EOL><center><h1>502 Bad Gateway</h1></center><EOL><EOL><hr><center>nginx/1.26.3</center><EOL><EOL></body><EOL><EOL></html><EOL><EOL>"
```
```
127.0.0.1 - - [21/Dec/2025:11:11:05 +0100] "GET /13/4292/2781.png HTTP/1.1" 502 157 "-" "Java/25.0.1"
```

Checking even from external, I can access tile 0/0/0.png just fine via wget also via browser:

```bash
# wget --spider http://127.0.0.1/0/0/0.png
Spider mode enabled. Check if remote file exists.
--2025-12-21 11:13:50--  http://127.0.0.1/0/0/0.png
Connecting to 127.0.0.1:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 6924 (6.8K) [image/png]
Remote file exists.
```
<img width="479" height="387" alt="Image" src="https://github.com/user-attachments/assets/09bc476c-4ec6-4194-a652-9b90b69d5df0" />

I'd happily share a video, though I'm not confortable sharing my exact location publicly, so please let me know if I can send it to you in any other way, if needed ^^



EDIT: After leaving it open for roughly 15minutes, things seem to have stabilized and I don't see the error that often anymore, it seems to happen only when moving to new places quickly, but still it's "spammed" a lot of times in the log.

Could this maybe be a rate-limit from osm?

**Comment by dgraf-gh** [comment]
No need for a video here. :)

Never experienced this. For development I have the nginx running in a container and access it view http://localhost:8084/ and this works reliably. It is as close as I get to the proxmkx setup. Let me play around a little bit when I have time today, maybe there is some work todo here.

**Comment by dgraf-gh** [comment]
Good morning,

Yesterday, I tried to clear the cache, but with no luck. Without any way to reproduce this behavior, I would suggest simply skipping the cache in that case. It is not a deal-breaker in my opinion, only nice to have.

Maybe in the future, I will come up with a better solution or accidentally stumble upon the problem on my own.

Is this OK for you?

**Comment by CrazyWolf13** [comment]
Yeah sure :)

I'll try too keep an eye on it if I find any reportable consistent occurende of the issue.

**Comment by ytzelf** [comment]
Hi

Had a problem as well, fixed it by giving the tile caching container a network alias to the default "tile-cache" in docker compose as such:
```
  reitti_tile-cache:
    restart: unless-stopped
    networks:
      <your network name>:
        aliases:
          - tile-cache
```

**Comment by dgraf-gh** [comment]
Hello @ytzelf,

thank you for the information. 

> Had a problem as well, fixed it by giving the tile caching container a network alias to the default "tile-cache" in docker compose as such:
> 
> ```
>   reitti_tile-cache:
>     restart: unless-stopped
>     networks:
>       <your network name>:
>         aliases:
>           - tile-cache
> ```

Shouldn't this not be the default? Or is proxmox running them outside of docker compose?

**Comment by CrazyWolf13** [comment]
@dgraf-gh 

Yes, the proxmox community-script runs them without docker, however the above does not seem related to community-scripts and looks like a normal docker deployment

**Comment by dgraf-gh** [comment]
Thank you again for the explainer :)
